using Shadowchats.Conversations.Application.IntegrationEvents;

namespace Shadowchats.Conversations.Application.Interfaces;

public interface IInboxIntegrationEventContainerRepository : IRepository<InboxIntegrationEventContainer>;