using Shadowchats.Conversations.Application.IntegrationEvents;

namespace Shadowchats.Conversations.Application.Interfaces;

public interface IOutboxIntegrationEventContainerRepository : IRepository<OutboxIntegrationEventContainer>;